name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Push changes
        run: |
          git remote set-url origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/your-username/your-repo.git
          git add .
          git commit -m "Update docs"
          git push origin main
    
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc

      - name: Check Pandoc version
        run: pandoc --version

      - name: Install dependencies
        run: |
          pip install sphinx sphinx-rtd-theme nbsphinx myst_parser

      - name: Build Sphinx Docs
        run: |
          sphinx-build -b html source build/html

      - name: Deploy to GitHub Pages (docs folder)
        run: |
          mkdir -p docs
          cp -r build/html/* docs/
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/
          git commit -m "Update Sphinx docs"
          git push
